clean:
	rm -r test/txt/*
	rm -r test/models/*
	rm -r test/results/*
	find . -name '*.DS_Store' -type f -delete

clean2:
	rm -r test2/txt/*
	rm -r test2/models/*
	rm -r test2/results/*
	find . -name '*.DS_Store' -type f -delete


models_clean:
	rm -r test/models/*

results_clean:
	rm -r test/results/*
